<?php
/**
 * Country and continent reference data.
 *
 * @package GeoBlocker
 */

namespace GeoBlocker\Geo;

defined( 'ABSPATH' ) || exit;

/**
 * ISO 3166-1 alpha-2 countries with their continent.
 *
 * The continent map is used when a provider only returns a country code
 * (for example Cloudflare's CF-IPCountry header). When the GeoIP database
 * returns its own continent, that value is used instead.
 */
final class Countries {

	/**
	 * Special pseudo-country used by Cloudflare for Tor exit nodes.
	 */
	public const TOR = 'T1';

	/**
	 * Country code => continent code.
	 */
	private const CONTINENT_MAP = array(
		'AD' => 'EU',
		'AE' => 'AS',
		'AF' => 'AS',
		'AG' => 'NA',
		'AI' => 'NA',
		'AL' => 'EU',
		'AM' => 'AS',
		'AO' => 'AF',
		'AQ' => 'AN',
		'AR' => 'SA',
		'AS' => 'OC',
		'AT' => 'EU',
		'AU' => 'OC',
		'AW' => 'NA',
		'AX' => 'EU',
		'AZ' => 'AS',
		'BA' => 'EU',
		'BB' => 'NA',
		'BD' => 'AS',
		'BE' => 'EU',
		'BF' => 'AF',
		'BG' => 'EU',
		'BH' => 'AS',
		'BI' => 'AF',
		'BJ' => 'AF',
		'BL' => 'NA',
		'BM' => 'NA',
		'BN' => 'AS',
		'BO' => 'SA',
		'BQ' => 'NA',
		'BR' => 'SA',
		'BS' => 'NA',
		'BT' => 'AS',
		'BV' => 'AN',
		'BW' => 'AF',
		'BY' => 'EU',
		'BZ' => 'NA',
		'CA' => 'NA',
		'CC' => 'AS',
		'CD' => 'AF',
		'CF' => 'AF',
		'CG' => 'AF',
		'CH' => 'EU',
		'CI' => 'AF',
		'CK' => 'OC',
		'CL' => 'SA',
		'CM' => 'AF',
		'CN' => 'AS',
		'CO' => 'SA',
		'CR' => 'NA',
		'CU' => 'NA',
		'CV' => 'AF',
		'CW' => 'NA',
		'CX' => 'AS',
		'CY' => 'EU',
		'CZ' => 'EU',
		'DE' => 'EU',
		'DJ' => 'AF',
		'DK' => 'EU',
		'DM' => 'NA',
		'DO' => 'NA',
		'DZ' => 'AF',
		'EC' => 'SA',
		'EE' => 'EU',
		'EG' => 'AF',
		'EH' => 'AF',
		'ER' => 'AF',
		'ES' => 'EU',
		'ET' => 'AF',
		'FI' => 'EU',
		'FJ' => 'OC',
		'FK' => 'SA',
		'FM' => 'OC',
		'FO' => 'EU',
		'FR' => 'EU',
		'GA' => 'AF',
		'GB' => 'EU',
		'GD' => 'NA',
		'GE' => 'AS',
		'GF' => 'SA',
		'GG' => 'EU',
		'GH' => 'AF',
		'GI' => 'EU',
		'GL' => 'NA',
		'GM' => 'AF',
		'GN' => 'AF',
		'GP' => 'NA',
		'GQ' => 'AF',
		'GR' => 'EU',
		'GS' => 'AN',
		'GT' => 'NA',
		'GU' => 'OC',
		'GW' => 'AF',
		'GY' => 'SA',
		'HK' => 'AS',
		'HM' => 'AN',
		'HN' => 'NA',
		'HR' => 'EU',
		'HT' => 'NA',
		'HU' => 'EU',
		'ID' => 'AS',
		'IE' => 'EU',
		'IL' => 'AS',
		'IM' => 'EU',
		'IN' => 'AS',
		'IO' => 'AS',
		'IQ' => 'AS',
		'IR' => 'AS',
		'IS' => 'EU',
		'IT' => 'EU',
		'JE' => 'EU',
		'JM' => 'NA',
		'JO' => 'AS',
		'JP' => 'AS',
		'KE' => 'AF',
		'KG' => 'AS',
		'KH' => 'AS',
		'KI' => 'OC',
		'KM' => 'AF',
		'KN' => 'NA',
		'KP' => 'AS',
		'KR' => 'AS',
		'KW' => 'AS',
		'KY' => 'NA',
		'KZ' => 'AS',
		'LA' => 'AS',
		'LB' => 'AS',
		'LC' => 'NA',
		'LI' => 'EU',
		'LK' => 'AS',
		'LR' => 'AF',
		'LS' => 'AF',
		'LT' => 'EU',
		'LU' => 'EU',
		'LV' => 'EU',
		'LY' => 'AF',
		'MA' => 'AF',
		'MC' => 'EU',
		'MD' => 'EU',
		'ME' => 'EU',
		'MF' => 'NA',
		'MG' => 'AF',
		'MH' => 'OC',
		'MK' => 'EU',
		'ML' => 'AF',
		'MM' => 'AS',
		'MN' => 'AS',
		'MO' => 'AS',
		'MP' => 'OC',
		'MQ' => 'NA',
		'MR' => 'AF',
		'MS' => 'NA',
		'MT' => 'EU',
		'MU' => 'AF',
		'MV' => 'AS',
		'MW' => 'AF',
		'MX' => 'NA',
		'MY' => 'AS',
		'MZ' => 'AF',
		'NA' => 'AF',
		'NC' => 'OC',
		'NE' => 'AF',
		'NF' => 'OC',
		'NG' => 'AF',
		'NI' => 'NA',
		'NL' => 'EU',
		'NO' => 'EU',
		'NP' => 'AS',
		'NR' => 'OC',
		'NU' => 'OC',
		'NZ' => 'OC',
		'OM' => 'AS',
		'PA' => 'NA',
		'PE' => 'SA',
		'PF' => 'OC',
		'PG' => 'OC',
		'PH' => 'AS',
		'PK' => 'AS',
		'PL' => 'EU',
		'PM' => 'NA',
		'PN' => 'OC',
		'PR' => 'NA',
		'PS' => 'AS',
		'PT' => 'EU',
		'PW' => 'OC',
		'PY' => 'SA',
		'QA' => 'AS',
		'RE' => 'AF',
		'RO' => 'EU',
		'RS' => 'EU',
		'RU' => 'EU',
		'RW' => 'AF',
		'SA' => 'AS',
		'SB' => 'OC',
		'SC' => 'AF',
		'SD' => 'AF',
		'SE' => 'EU',
		'SG' => 'AS',
		'SH' => 'AF',
		'SI' => 'EU',
		'SJ' => 'EU',
		'SK' => 'EU',
		'SL' => 'AF',
		'SM' => 'EU',
		'SN' => 'AF',
		'SO' => 'AF',
		'SR' => 'SA',
		'SS' => 'AF',
		'ST' => 'AF',
		'SV' => 'NA',
		'SX' => 'NA',
		'SY' => 'AS',
		'SZ' => 'AF',
		'TC' => 'NA',
		'TD' => 'AF',
		'TF' => 'AN',
		'TG' => 'AF',
		'TH' => 'AS',
		'TJ' => 'AS',
		'TK' => 'OC',
		'TL' => 'AS',
		'TM' => 'AS',
		'TN' => 'AF',
		'TO' => 'OC',
		'TR' => 'AS',
		'TT' => 'NA',
		'TV' => 'OC',
		'TW' => 'AS',
		'TZ' => 'AF',
		'UA' => 'EU',
		'UG' => 'AF',
		'UM' => 'OC',
		'US' => 'NA',
		'UY' => 'SA',
		'UZ' => 'AS',
		'VA' => 'EU',
		'VC' => 'NA',
		'VE' => 'SA',
		'VG' => 'NA',
		'VI' => 'NA',
		'VN' => 'AS',
		'VU' => 'OC',
		'WF' => 'OC',
		'WS' => 'OC',
		'XK' => 'EU',
		'YE' => 'AS',
		'YT' => 'AF',
		'ZA' => 'AF',
		'ZM' => 'AF',
		'ZW' => 'AF',
		'T1' => '',
	);

	/**
	 * Translated country names, built lazily (admin only).
	 *
	 * @var array<string,string>|null
	 */
	private static ?array $names = null;

	/**
	 * Country code => continent code map.
	 *
	 * @return array<string,string>
	 */
	public static function continent_map(): array {
		return self::CONTINENT_MAP;
	}

	/**
	 * Continent code for a country code, or '' when unknown.
	 *
	 * @param string $country_code ISO 3166-1 alpha-2 code.
	 */
	public static function continent_for( string $country_code ): string {
		return self::CONTINENT_MAP[ strtoupper( $country_code ) ] ?? '';
	}

	/**
	 * Whether a code is a known country code.
	 *
	 * @param string $country_code Code to check.
	 */
	public static function is_valid( string $country_code ): bool {
		return isset( self::CONTINENT_MAP[ strtoupper( $country_code ) ] );
	}

	/**
	 * Continent code => translated name.
	 *
	 * @return array<string,string>
	 */
	public static function continent_codes(): array {
		return array(
			'AF' => __( 'Africa', 'geoblocker' ),
			'AN' => __( 'Antarctica', 'geoblocker' ),
			'AS' => __( 'Asia', 'geoblocker' ),
			'EU' => __( 'Europe', 'geoblocker' ),
			'NA' => __( 'North America', 'geoblocker' ),
			'OC' => __( 'Oceania', 'geoblocker' ),
			'SA' => __( 'South America', 'geoblocker' ),
		);
	}

	/**
	 * Translated continent name.
	 *
	 * @param string $code Continent code.
	 */
	public static function continent_name( string $code ): string {
		$all = self::continent_codes();
		return $all[ strtoupper( $code ) ] ?? ( '' === $code ? __( 'Unknown', 'geoblocker' ) : $code );
	}

	/**
	 * Translated country name.
	 *
	 * @param string $code Country code.
	 */
	public static function country_name( string $code ): string {
		$all = self::names();
		return $all[ strtoupper( $code ) ] ?? ( '' === $code ? __( 'Unknown', 'geoblocker' ) : $code );
	}

	/**
	 * All countries: code => translated name, sorted by name.
	 *
	 * @return array<string,string>
	 */
	public static function names(): array {
		if ( null !== self::$names ) {
			return self::$names;
		}

		$names = array(
			'AD' => __( 'Andorra', 'geoblocker' ),
			'AE' => __( 'United Arab Emirates', 'geoblocker' ),
			'AF' => __( 'Afghanistan', 'geoblocker' ),
			'AG' => __( 'Antigua and Barbuda', 'geoblocker' ),
			'AI' => __( 'Anguilla', 'geoblocker' ),
			'AL' => __( 'Albania', 'geoblocker' ),
			'AM' => __( 'Armenia', 'geoblocker' ),
			'AO' => __( 'Angola', 'geoblocker' ),
			'AQ' => __( 'Antarctica', 'geoblocker' ),
			'AR' => __( 'Argentina', 'geoblocker' ),
			'AS' => __( 'American Samoa', 'geoblocker' ),
			'AT' => __( 'Austria', 'geoblocker' ),
			'AU' => __( 'Australia', 'geoblocker' ),
			'AW' => __( 'Aruba', 'geoblocker' ),
			'AX' => __( 'Åland Islands', 'geoblocker' ),
			'AZ' => __( 'Azerbaijan', 'geoblocker' ),
			'BA' => __( 'Bosnia and Herzegovina', 'geoblocker' ),
			'BB' => __( 'Barbados', 'geoblocker' ),
			'BD' => __( 'Bangladesh', 'geoblocker' ),
			'BE' => __( 'Belgium', 'geoblocker' ),
			'BF' => __( 'Burkina Faso', 'geoblocker' ),
			'BG' => __( 'Bulgaria', 'geoblocker' ),
			'BH' => __( 'Bahrain', 'geoblocker' ),
			'BI' => __( 'Burundi', 'geoblocker' ),
			'BJ' => __( 'Benin', 'geoblocker' ),
			'BL' => __( 'Saint Barthélemy', 'geoblocker' ),
			'BM' => __( 'Bermuda', 'geoblocker' ),
			'BN' => __( 'Brunei', 'geoblocker' ),
			'BO' => __( 'Bolivia', 'geoblocker' ),
			'BQ' => __( 'Caribbean Netherlands', 'geoblocker' ),
			'BR' => __( 'Brazil', 'geoblocker' ),
			'BS' => __( 'Bahamas', 'geoblocker' ),
			'BT' => __( 'Bhutan', 'geoblocker' ),
			'BV' => __( 'Bouvet Island', 'geoblocker' ),
			'BW' => __( 'Botswana', 'geoblocker' ),
			'BY' => __( 'Belarus', 'geoblocker' ),
			'BZ' => __( 'Belize', 'geoblocker' ),
			'CA' => __( 'Canada', 'geoblocker' ),
			'CC' => __( 'Cocos (Keeling) Islands', 'geoblocker' ),
			'CD' => __( 'Congo (DRC)', 'geoblocker' ),
			'CF' => __( 'Central African Republic', 'geoblocker' ),
			'CG' => __( 'Congo (Republic)', 'geoblocker' ),
			'CH' => __( 'Switzerland', 'geoblocker' ),
			'CI' => __( 'Côte d’Ivoire', 'geoblocker' ),
			'CK' => __( 'Cook Islands', 'geoblocker' ),
			'CL' => __( 'Chile', 'geoblocker' ),
			'CM' => __( 'Cameroon', 'geoblocker' ),
			'CN' => __( 'China', 'geoblocker' ),
			'CO' => __( 'Colombia', 'geoblocker' ),
			'CR' => __( 'Costa Rica', 'geoblocker' ),
			'CU' => __( 'Cuba', 'geoblocker' ),
			'CV' => __( 'Cabo Verde', 'geoblocker' ),
			'CW' => __( 'Curaçao', 'geoblocker' ),
			'CX' => __( 'Christmas Island', 'geoblocker' ),
			'CY' => __( 'Cyprus', 'geoblocker' ),
			'CZ' => __( 'Czechia', 'geoblocker' ),
			'DE' => __( 'Germany', 'geoblocker' ),
			'DJ' => __( 'Djibouti', 'geoblocker' ),
			'DK' => __( 'Denmark', 'geoblocker' ),
			'DM' => __( 'Dominica', 'geoblocker' ),
			'DO' => __( 'Dominican Republic', 'geoblocker' ),
			'DZ' => __( 'Algeria', 'geoblocker' ),
			'EC' => __( 'Ecuador', 'geoblocker' ),
			'EE' => __( 'Estonia', 'geoblocker' ),
			'EG' => __( 'Egypt', 'geoblocker' ),
			'EH' => __( 'Western Sahara', 'geoblocker' ),
			'ER' => __( 'Eritrea', 'geoblocker' ),
			'ES' => __( 'Spain', 'geoblocker' ),
			'ET' => __( 'Ethiopia', 'geoblocker' ),
			'FI' => __( 'Finland', 'geoblocker' ),
			'FJ' => __( 'Fiji', 'geoblocker' ),
			'FK' => __( 'Falkland Islands', 'geoblocker' ),
			'FM' => __( 'Micronesia', 'geoblocker' ),
			'FO' => __( 'Faroe Islands', 'geoblocker' ),
			'FR' => __( 'France', 'geoblocker' ),
			'GA' => __( 'Gabon', 'geoblocker' ),
			'GB' => __( 'United Kingdom', 'geoblocker' ),
			'GD' => __( 'Grenada', 'geoblocker' ),
			'GE' => __( 'Georgia', 'geoblocker' ),
			'GF' => __( 'French Guiana', 'geoblocker' ),
			'GG' => __( 'Guernsey', 'geoblocker' ),
			'GH' => __( 'Ghana', 'geoblocker' ),
			'GI' => __( 'Gibraltar', 'geoblocker' ),
			'GL' => __( 'Greenland', 'geoblocker' ),
			'GM' => __( 'Gambia', 'geoblocker' ),
			'GN' => __( 'Guinea', 'geoblocker' ),
			'GP' => __( 'Guadeloupe', 'geoblocker' ),
			'GQ' => __( 'Equatorial Guinea', 'geoblocker' ),
			'GR' => __( 'Greece', 'geoblocker' ),
			'GS' => __( 'South Georgia and the South Sandwich Islands', 'geoblocker' ),
			'GT' => __( 'Guatemala', 'geoblocker' ),
			'GU' => __( 'Guam', 'geoblocker' ),
			'GW' => __( 'Guinea-Bissau', 'geoblocker' ),
			'GY' => __( 'Guyana', 'geoblocker' ),
			'HK' => __( 'Hong Kong', 'geoblocker' ),
			'HM' => __( 'Heard Island and McDonald Islands', 'geoblocker' ),
			'HN' => __( 'Honduras', 'geoblocker' ),
			'HR' => __( 'Croatia', 'geoblocker' ),
			'HT' => __( 'Haiti', 'geoblocker' ),
			'HU' => __( 'Hungary', 'geoblocker' ),
			'ID' => __( 'Indonesia', 'geoblocker' ),
			'IE' => __( 'Ireland', 'geoblocker' ),
			'IL' => __( 'Israel', 'geoblocker' ),
			'IM' => __( 'Isle of Man', 'geoblocker' ),
			'IN' => __( 'India', 'geoblocker' ),
			'IO' => __( 'British Indian Ocean Territory', 'geoblocker' ),
			'IQ' => __( 'Iraq', 'geoblocker' ),
			'IR' => __( 'Iran', 'geoblocker' ),
			'IS' => __( 'Iceland', 'geoblocker' ),
			'IT' => __( 'Italy', 'geoblocker' ),
			'JE' => __( 'Jersey', 'geoblocker' ),
			'JM' => __( 'Jamaica', 'geoblocker' ),
			'JO' => __( 'Jordan', 'geoblocker' ),
			'JP' => __( 'Japan', 'geoblocker' ),
			'KE' => __( 'Kenya', 'geoblocker' ),
			'KG' => __( 'Kyrgyzstan', 'geoblocker' ),
			'KH' => __( 'Cambodia', 'geoblocker' ),
			'KI' => __( 'Kiribati', 'geoblocker' ),
			'KM' => __( 'Comoros', 'geoblocker' ),
			'KN' => __( 'Saint Kitts and Nevis', 'geoblocker' ),
			'KP' => __( 'North Korea', 'geoblocker' ),
			'KR' => __( 'South Korea', 'geoblocker' ),
			'KW' => __( 'Kuwait', 'geoblocker' ),
			'KY' => __( 'Cayman Islands', 'geoblocker' ),
			'KZ' => __( 'Kazakhstan', 'geoblocker' ),
			'LA' => __( 'Laos', 'geoblocker' ),
			'LB' => __( 'Lebanon', 'geoblocker' ),
			'LC' => __( 'Saint Lucia', 'geoblocker' ),
			'LI' => __( 'Liechtenstein', 'geoblocker' ),
			'LK' => __( 'Sri Lanka', 'geoblocker' ),
			'LR' => __( 'Liberia', 'geoblocker' ),
			'LS' => __( 'Lesotho', 'geoblocker' ),
			'LT' => __( 'Lithuania', 'geoblocker' ),
			'LU' => __( 'Luxembourg', 'geoblocker' ),
			'LV' => __( 'Latvia', 'geoblocker' ),
			'LY' => __( 'Libya', 'geoblocker' ),
			'MA' => __( 'Morocco', 'geoblocker' ),
			'MC' => __( 'Monaco', 'geoblocker' ),
			'MD' => __( 'Moldova', 'geoblocker' ),
			'ME' => __( 'Montenegro', 'geoblocker' ),
			'MF' => __( 'Saint Martin', 'geoblocker' ),
			'MG' => __( 'Madagascar', 'geoblocker' ),
			'MH' => __( 'Marshall Islands', 'geoblocker' ),
			'MK' => __( 'North Macedonia', 'geoblocker' ),
			'ML' => __( 'Mali', 'geoblocker' ),
			'MM' => __( 'Myanmar', 'geoblocker' ),
			'MN' => __( 'Mongolia', 'geoblocker' ),
			'MO' => __( 'Macao', 'geoblocker' ),
			'MP' => __( 'Northern Mariana Islands', 'geoblocker' ),
			'MQ' => __( 'Martinique', 'geoblocker' ),
			'MR' => __( 'Mauritania', 'geoblocker' ),
			'MS' => __( 'Montserrat', 'geoblocker' ),
			'MT' => __( 'Malta', 'geoblocker' ),
			'MU' => __( 'Mauritius', 'geoblocker' ),
			'MV' => __( 'Maldives', 'geoblocker' ),
			'MW' => __( 'Malawi', 'geoblocker' ),
			'MX' => __( 'Mexico', 'geoblocker' ),
			'MY' => __( 'Malaysia', 'geoblocker' ),
			'MZ' => __( 'Mozambique', 'geoblocker' ),
			'NA' => __( 'Namibia', 'geoblocker' ),
			'NC' => __( 'New Caledonia', 'geoblocker' ),
			'NE' => __( 'Niger', 'geoblocker' ),
			'NF' => __( 'Norfolk Island', 'geoblocker' ),
			'NG' => __( 'Nigeria', 'geoblocker' ),
			'NI' => __( 'Nicaragua', 'geoblocker' ),
			'NL' => __( 'Netherlands', 'geoblocker' ),
			'NO' => __( 'Norway', 'geoblocker' ),
			'NP' => __( 'Nepal', 'geoblocker' ),
			'NR' => __( 'Nauru', 'geoblocker' ),
			'NU' => __( 'Niue', 'geoblocker' ),
			'NZ' => __( 'New Zealand', 'geoblocker' ),
			'OM' => __( 'Oman', 'geoblocker' ),
			'PA' => __( 'Panama', 'geoblocker' ),
			'PE' => __( 'Peru', 'geoblocker' ),
			'PF' => __( 'French Polynesia', 'geoblocker' ),
			'PG' => __( 'Papua New Guinea', 'geoblocker' ),
			'PH' => __( 'Philippines', 'geoblocker' ),
			'PK' => __( 'Pakistan', 'geoblocker' ),
			'PL' => __( 'Poland', 'geoblocker' ),
			'PM' => __( 'Saint Pierre and Miquelon', 'geoblocker' ),
			'PN' => __( 'Pitcairn Islands', 'geoblocker' ),
			'PR' => __( 'Puerto Rico', 'geoblocker' ),
			'PS' => __( 'Palestine', 'geoblocker' ),
			'PT' => __( 'Portugal', 'geoblocker' ),
			'PW' => __( 'Palau', 'geoblocker' ),
			'PY' => __( 'Paraguay', 'geoblocker' ),
			'QA' => __( 'Qatar', 'geoblocker' ),
			'RE' => __( 'Réunion', 'geoblocker' ),
			'RO' => __( 'Romania', 'geoblocker' ),
			'RS' => __( 'Serbia', 'geoblocker' ),
			'RU' => __( 'Russia', 'geoblocker' ),
			'RW' => __( 'Rwanda', 'geoblocker' ),
			'SA' => __( 'Saudi Arabia', 'geoblocker' ),
			'SB' => __( 'Solomon Islands', 'geoblocker' ),
			'SC' => __( 'Seychelles', 'geoblocker' ),
			'SD' => __( 'Sudan', 'geoblocker' ),
			'SE' => __( 'Sweden', 'geoblocker' ),
			'SG' => __( 'Singapore', 'geoblocker' ),
			'SH' => __( 'Saint Helena, Ascension and Tristan da Cunha', 'geoblocker' ),
			'SI' => __( 'Slovenia', 'geoblocker' ),
			'SJ' => __( 'Svalbard and Jan Mayen', 'geoblocker' ),
			'SK' => __( 'Slovakia', 'geoblocker' ),
			'SL' => __( 'Sierra Leone', 'geoblocker' ),
			'SM' => __( 'San Marino', 'geoblocker' ),
			'SN' => __( 'Senegal', 'geoblocker' ),
			'SO' => __( 'Somalia', 'geoblocker' ),
			'SR' => __( 'Suriname', 'geoblocker' ),
			'SS' => __( 'South Sudan', 'geoblocker' ),
			'ST' => __( 'São Tomé and Príncipe', 'geoblocker' ),
			'SV' => __( 'El Salvador', 'geoblocker' ),
			'SX' => __( 'Sint Maarten', 'geoblocker' ),
			'SY' => __( 'Syria', 'geoblocker' ),
			'SZ' => __( 'Eswatini', 'geoblocker' ),
			'TC' => __( 'Turks and Caicos Islands', 'geoblocker' ),
			'TD' => __( 'Chad', 'geoblocker' ),
			'TF' => __( 'French Southern Territories', 'geoblocker' ),
			'TG' => __( 'Togo', 'geoblocker' ),
			'TH' => __( 'Thailand', 'geoblocker' ),
			'TJ' => __( 'Tajikistan', 'geoblocker' ),
			'TK' => __( 'Tokelau', 'geoblocker' ),
			'TL' => __( 'Timor-Leste', 'geoblocker' ),
			'TM' => __( 'Turkmenistan', 'geoblocker' ),
			'TN' => __( 'Tunisia', 'geoblocker' ),
			'TO' => __( 'Tonga', 'geoblocker' ),
			'TR' => __( 'Türkiye', 'geoblocker' ),
			'TT' => __( 'Trinidad and Tobago', 'geoblocker' ),
			'TV' => __( 'Tuvalu', 'geoblocker' ),
			'TW' => __( 'Taiwan', 'geoblocker' ),
			'TZ' => __( 'Tanzania', 'geoblocker' ),
			'UA' => __( 'Ukraine', 'geoblocker' ),
			'UG' => __( 'Uganda', 'geoblocker' ),
			'UM' => __( 'U.S. Outlying Islands', 'geoblocker' ),
			'US' => __( 'United States', 'geoblocker' ),
			'UY' => __( 'Uruguay', 'geoblocker' ),
			'UZ' => __( 'Uzbekistan', 'geoblocker' ),
			'VA' => __( 'Vatican City', 'geoblocker' ),
			'VC' => __( 'Saint Vincent and the Grenadines', 'geoblocker' ),
			'VE' => __( 'Venezuela', 'geoblocker' ),
			'VG' => __( 'British Virgin Islands', 'geoblocker' ),
			'VI' => __( 'U.S. Virgin Islands', 'geoblocker' ),
			'VN' => __( 'Vietnam', 'geoblocker' ),
			'VU' => __( 'Vanuatu', 'geoblocker' ),
			'WF' => __( 'Wallis and Futuna', 'geoblocker' ),
			'WS' => __( 'Samoa', 'geoblocker' ),
			'XK' => __( 'Kosovo', 'geoblocker' ),
			'YE' => __( 'Yemen', 'geoblocker' ),
			'YT' => __( 'Mayotte', 'geoblocker' ),
			'ZA' => __( 'South Africa', 'geoblocker' ),
			'ZM' => __( 'Zambia', 'geoblocker' ),
			'ZW' => __( 'Zimbabwe', 'geoblocker' ),
			'T1' => __( 'Tor network (Cloudflare only)', 'geoblocker' ),
		);

		if ( function_exists( 'collator_create' ) ) {
			$collator = collator_create( get_locale() );
			if ( $collator ) {
				uasort( $names, array( $collator, 'compare' ) );
			} else {
				asort( $names, SORT_NATURAL | SORT_FLAG_CASE );
			}
		} else {
			asort( $names, SORT_NATURAL | SORT_FLAG_CASE );
		}

		self::$names = $names;
		return $names;
	}
}
